# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/20c49349-f062-437d-adbc-fbdfde5b4ef1";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a9660b4e-151c-41bd-94aa-8ae661ebd917".device = "/dev/disk/by-uuid/a9660b4e-151c-41bd-94aa-8ae661ebd917";
  boot.initrd.luks.devices."luks-21da88b2-7829-4c08-8afd-2b4eb081e9b6".device = "/dev/disk/by-uuid/21da88b2-7829-4c08-8afd-2b4eb081e9b6";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F3A9-820B";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/17464c94-1639-4011-a1ac-2c3493e16203";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp12s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
