# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/00a16d26-57a7-420d-ad7e-b571cecdc3e3";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-3a0cffa8-43bc-4a08-985f-fc43630d99df".device = "/dev/disk/by-uuid/3a0cffa8-43bc-4a08-985f-fc43630d99df";
  boot.initrd.luks.devices."luks-49097901-7cd3-4cad-af63-4db6ba858b30".device = "/dev/disk/by-uuid/49097901-7cd3-4cad-af63-4db6ba858b30";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C853-0FAE";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/c444adff-24a7-4da1-98e6-00e2e62262eb";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp61s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
