#!/bin/sh

function handle {
    focused_workspace=$(hyprctl monitors -j | jq '.[] | select(.focused).activeWorkspace.id')
    echo $(hyprctl workspaces -j | jq ".[] |= {id: .id, mon: .monitor, focused: (.id == $focused_workspace)} | sort_by(.id)")
}

socat -U - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do handle $line; done
