#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super+Shift Return spawn foot

# Super+Q to close the focused view
riverctl map normal Super+Shift Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift C exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super N focus-view next
riverctl map normal Super E focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift E swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
# riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
# riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift I send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt N move down 100
riverctl map normal Super+Alt E move up 100
riverctl map normal Super+Alt I move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control N snap down
riverctl map normal Super+Alt+Control E snap up
riverctl map normal Super+Alt+Control I snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift N resize vertical 100
riverctl map normal Super+Alt+Shift E resize vertical -100
riverctl map normal Super+Alt+Shift I resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
# riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
# riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    # riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    # riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    # riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    # riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
# riverctl background-color 0x002b36
# riverctl border-color-focused 0x93a1a1
# riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

######
######

# VARS 
background=212121
foreground=EEFFFF
focus=FF5370

bemenu="-i -p '' -H 19 \
     --fn 'Ubuntu bold 11' \
     --tb '#${background}' \
     --tf '#${foreground}' \
     --fb '#${background}' \
     --ff '#${foreground}' \
     --nb '#${background}' \
     --nf '#${foreground}' \
     --hb '#${focus}' \
     --hf '#${background}' \
     --sb '#${background}' \
     --sf '#${foreground}'"

# SETTINGS
riverctl set-cursor-warp on-output-change
riverctl focus-follows-cursor normal
riverctl border-color-focused 0x$focus
riverctl border-color-unfocused 0x$background
riverctl background-color 0x$background
riverctl input "2:14:ETPS/2_Elantech_Touchpad" tap enabled
riverctl input "2:14:ETPS/2_Elantech_Touchpad" natural-scroll enabled

# BINDS
# basics 
riverctl map normal Super S spawn "bemenu-run ${bemenu}"
riverctl map normal Super+Shift S spawn "xdg-open \"\$(fd --search-path ~ --search-path /run/media -tf | bemenu ${bemenu} -l 20)\""
riverctl map normal Super X spawn 'foot btm'
riverctl map normal Super Q spawm 'makoctl dismiss --all'
riverctl map normal Super+Shift A spawn 'foot alsamixer'
riverctl map normal Super A spawn 'foot pulsemixer'

# browsers 
riverctl map normal Super W spawn qutebrowser
riverctl map normal Super+Shift W spawn firefox

# audio 
for mode in normal locked; do
riverctl map normal None XF86AudioRaiseVolume spawn 'pulsemixer --change-volume +2'
riverctl map normal None XF86AudioLowerVolume spawn 'pulsemixer --change-volume -2'
riverctl map normal None XF86AudioMute spawn 'pulsemixer --toggle-mute'
riverctl map normal Shift XF86AudioMute spawn 'amixer set Capture toggle'
riverctl map normal Shift XF86AudioRaiseVolume spawn 'playerctl volume +2'
riverctl map normal Shift XF86AudioLowerVolume spawn 'playerctl volume -2'
done

# screenshots
riverctl map normal None Print spawn 'grim -g "$(slurp)" - | wl-copy'

# power
riverctl map normal Super F12 spawn 'systemctl -i poweroff'
riverctl map normal Super F11 spawn 'systemctl -i reboot'
riverctl map normal Super F10 spawn 'swaylock -c 000000'
riverctl map normal None XF86ScreenSaver spawn 'swaylock -c 000000'

# START
kanshi &
mako &
swaybg -i ~/.config/wall -m fill &  
yambar & # https://codeberg.org/dnkl/yambar/issues/148
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river &

######
######

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
# riverctl default-layout rivertile
# exec rivertile -view-padding 6 -outer-padding 6

## FROM: https://git.sr.ht/~novakane/rivercarro
# Mod+H and Mod+L to decrease/increase the main ratio of rivercarro
riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Super I send-layout-cmd rivercarro "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivercarro
riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Shift I send-layout-cmd rivercarro "main-count -1"

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left"
# And for monocle
riverctl map normal Super+Shift F send-layout-cmd rivercarro "main-location monocle"

# Add others rivercarrro's commands the same way with the keybinds you'd like.
# e.g.
riverctl map normal Super+Shift Left  send-layout-cmd rivercarro "inner-gaps -1"
riverctl map normal Super+Shift Right send-layout-cmd rivercarro "inner-gaps +1"
riverctl map normal Super+Shift Down  send-layout-cmd rivercarro "outer-gaps -1"
riverctl map normal Super+Shift Up    send-layout-cmd rivercarro "outer-gaps +1"
riverctl map normal Super U           send-layout-cmd rivercarro "main-ratio -0.01"
riverctl map normal Super Y           send-layout-cmd rivercarro "main-ratio +0.01"

# Set and exec into the default layout generator, rivercarro.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
exec rivercarro
