[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]


[language-server.nu-lsp]
command = "nu"
args = ["--lsp"]

[[language]]
name = "nu"
scope = "source.nu"
injection-regex = "nu"
file-types = ["nu"]
shebangs = ["nu"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = ["nu-lsp"]

[[language]]
name = "haskell"
formatter = { command = "stylish-haskell" }
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "nix"
formatter = { command = "alejandra" }
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [
  "vscode-html-language-server",
  "emmet-lsp",
  "tailwindcss-ls",
]

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "deno",
  # "typescript-language-server",
  "emmet-lsp",
  "tailwindcss-ls",
]
auto-format = true

[[language]]
name = "svelte"
formatter = { command = 'prettier', args = ["--parser", "svelte"] }
file-types = ["svelte"]
language-servers = ["tailwindcss-ls", "svelteserver"]
block-comment-tokens = { start = "<!--", end = "-->" }
comment-tokens = "//"
auto-format = true

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[language-server.deno]
command = "deno"
args = ["lsp"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "php"
auto-format = true
language-servers = ["phpactor"]

[language-server.phpactor]
command = "phpactor"
args = ["language-server"]
